
spring:
  application:
    name: user
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user
    username: postgres
    password: postgres
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
  data:
    redis:
      host: localhost
      port: 6379
#    password: redis
#    database: 0
#    timeout: 10s
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
server:
  port: 8080
  security:
    user:
      name: admin
      password: admin